apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: mrsaeidshakeri/order-service:1.0
        ports:
        - containerPort: 8004
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: e-commerce
spec:
  selector:
    run: order-service
  ports:
    - protocol: TCP
      port: 84
      targetPort: 8004
  type: LoadBalancer

