apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: mrsaeidshakeri/payment-service:1.0
        ports:
        - containerPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: e-commerce
spec:
  selector:
    run: payment-service
  ports:
    - protocol: TCP
      port: 83
      targetPort: 8003
  type: LoadBalancer

