version: '3.8'

services:
  product-service:
    image: mrsaeidshakeri/product-service:0.0
    build: .
    command: >
        sh -c "python manage.py runserver 0.0.0.0:8001"
    # command: >
    #     sh -c "python manage.py makemigrations && 
    #             python manage.py migrate && 
    #             python manage.py runserver 0.0.0.0:8001"
    volumes:
        - .:/code
    ports:
        - "8001:8001"
    depends_on:
        - db

  user-service:
    image: mrsaeidshakeri/user-service:0.0
    build: .
    command: >
      sh -c "python manage.py makemigrations && 
              python manage.py migrate && 
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  payment-service:
    image: mrsaeidshakeri/payment-service:0.0
    build: .
    command: >
        sh -c "python manage.py runserver 0.0.0.0:8002"
    # command: >
    #     sh -c "python manage.py makemigrations && 
    #             python manage.py migrate && 
    #             python manage.py runserver 0.0.0.0:8002"
    volumes:
        - .:/code
    ports:
        - "8002:8002"
    depends_on:
        - db

  order-service:
    image: mrsaeidshakeri/order-service:0.0
    build: .
    command: >
        sh -c "python manage.py runserver 0.0.0.0:8003"
    # command: >
    #     sh -c "python manage.py makemigrations && 
    #             python manage.py migrate && 
    #             python manage.py runserver 0.0.0.0:8003"
    volumes:
      - .:/code
    ports:
      - "8003:8003"
    depends_on:
      - db

  notification-service:
    image: mrsaeidshakeri/notification-service:0.0
    build: .
    command: >
        sh -c "python manage.py runserver 0.0.0.0:8004"
    # command: >
    #     sh -c "python manage.py makemigrations && 
    #             python manage.py migrate && 
    #             python manage.py runserver 0.0.0.0:8004"
    volumes:
        - .:/code
    ports:
        - "8004:8004"
    depends_on:
        - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
    driver: local
