apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: mrsaeidshakeri/notification-service:1.0
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: e-commerce
spec:
  selector:
    run: notification-service
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8002
  type: LoadBalancer

