apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: mrsaeidshakeri/product-service:1.0
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: e-commerce
spec:
  selector:
    run: product-service
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8001
  type: LoadBalancer

